language: node_js
node_js:
  - '10'

cache:
  directories:
    - 'node_modules'

script:
  - yarn build

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  committer-from-gh: true
  skip-cleanup: true
  keep-history: true
  local-dir: out
  repo: danakt/danakt.github.io
  target-branch: master
  on:
    branch: source
